title: assignment
description: to resort the source code of YUNDONGLI program
template:
  repo: assignment-template
  name: assignment
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
